apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: fetch-asset
  namespace: edt
spec:
  params:
  - name: URL
    description: URL of asset to fetch
    type: string
  - name: SHA256_CHECKSUM
    description: SHA256 checksum to verify asset download (if empty, don't verify)
    type: string
    default: ""
  - name: UNCOMPRESS
    description: uncompress asset (if compressed)
    type: string
    default: "false"
  - name: OUTPUT_FILENAME
    description: file name to give asset
    type: string
  steps:
  - name: fetch-asset
    image: 'compressors:latest'
    script: |
      #!/usr/bin/env bash
      set -ex
      FILENAME="$(params.URL)"
      FILENAME="${FILENAME%%\?*}"
      FILENAME="$(basename ${FILENAME})"
      curl --location --output "${FILENAME}" "$(params.URL)"

      if [[ ! -z "$(params.SHA256_CHECKSUM)" ]]; then
        SHA256=$(sha256sum "${FILENAME}" | cut -d' ' -f1)
        echo "sha256 of downloaded file: ${SHA256}"
        echo "sha256 expected: $(params.SHA256_CHECKSUM)"
        if [ "${SHA256}" != "$(params.SHA256_CHECKSUM)" ]; then
          exit -1
        fi
      fi

      if [ "$(params.UNCOMPRESS)" == "true" ]; then
        if [ "${FILENAME}" == *.xz ]; then
          xz --decompress "${FILENAME}"
          FILENAME=${FILENAME%.xz}
        fi
        if [ "${FILENAME}" == *.gz ]; then
          gunzip "${FILENAME}"
          FILENAME=${FILENAME%.gz}
        fi
      fi

      if [ "${FILENAME}" != "$(params.OUTPUT_FILENAME)" ]; then
        mv -- "${FILENAME}" "$(params.OUTPUT_FILENAME)"
      fi
    workingDir: $(workspaces.output.path)
  workspaces:
  - name: output