apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kubevirt-deploy-vm
  namespace: edt
spec:
  description: >-
    This task deploys a KubeVirt VM and waits until it is reachable via SSH.
    Requires a secret with both SSH private and public keys to be mounted
    as a workspace 'secrets'.
  params:
  - name: name
    description: 'VM name'
    type: string
  - name: namespace
    description: 'namespace'
    type: string
    default: $(context.taskRun.namespace)
  - name: cores
    description: 'cores'
    type: string
  - name: memory
    description: 'memory'
    type: string
  - name: diskimage
    description: 'containerDisk name or URL to import into dataVolume'
    type: string
  - name: storagesize
    description: 'size of data volume (if importing dataVolume from URL)'
    type: string
  - name: storageclass
    description: 'storage class of data volume (if importing dataVolume from URL)'
    type: string
  - name: verbose
    description: 'log the commands used during execution'
    type: string
    default: 'false'
  results:
    - name: ip
      description: IP address of the deployed VM
  steps:
  - name: deploy-vm
    image: 'image-registry.openshift-image-registry.svc:5000/openshift/cli:latest'
    script: |
      #!/usr/bin/env bash

      set -eu -o pipefail

      if [[ "$(params.verbose)" == "true" ]] ; then
        set -x
      fi

      SSH_PUB_KEY=$(cat "/tekton/home/ssh-key-pair/ssh-publickey")

      cat <<-EOF > userdata
      #cloud-config
      user: redhat
      password: redhat
      chpasswd: { expire: False }
      ssh_pwauth: False
      ssh_authorized_keys:
        - ${SSH_PUB_KEY}
      EOF

      if [[ "$(params.diskimage)" =~ '://' ]]; then
      cat <<-EOF > rootdisk
              - name: rootdisk
                dataVolume:
                  name: $(params.name)-rootdisk
        dataVolumeTemplates:
          - apiVersion: cdi.kubevirt.io/v1alpha1
            kind: DataVolume
            metadata:
              name: $(params.name)-rootdisk
            spec:
              pvc:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: $(params.storagesize)
                storageClassName: $(params.storageclass)
                volumeMode: Filesystem
              source:
                http:
                  url: >-
                    $(params.diskimage)
      EOF
      else
      cat <<-EOF > rootdisk
              - name: rootdisk
                containerDisk:
                  image: $(params.diskimage)
      EOF
      fi

      cat <<-EOF | tee vm.yaml
      apiVersion: kubevirt.io/v1alpha3
      kind: VirtualMachine
      metadata:
        name: $(params.name)
        namespace: $(params.namespace)
      spec:
        running: true
        template:
          metadata:
            name: $(params.name)
          spec:
            domain:
              cpu:
                cores: $(params.cores)
                sockets: 1
                threads: 1
              devices:
                disks:
                  - name: rootdisk
                    bootOrder: 1
                    disk:
                      bus: virtio
                  - name: cloudinitdisk
                    disk:
                      bus: virtio
              resources:
                requests:
                  memory: $(params.memory)
            hostname: $(params.name)
            terminationGracePeriodSeconds: 180
            volumes:
              - name: cloudinitdisk
                cloudInitNoCloud:
                  userDataBase64: $(cat userdata | base64 -w0)
      $(cat rootdisk)
      EOF

      oc apply -f vm.yaml

      IP=''

      START_TIME=${SECONDS}
      while true; do
        IP=$(oc get pods -n edt -o wide | { grep virt-launcher-build-release-ushift-main || test $? = 1; } | awk '{print $6}')
        test ! -z "${IP}" && test "${IP}" != "<none>" && break
        echo "Waiting for VM to start... $((${SECONDS} - ${START_TIME}))s"
        sleep 5
      done

      echo -n "${IP}" | tee $(results.ip.path)
  - name: waitfor-vm
    image: 'ssh:latest'
    script: |
      #!/usr/bin/env bash

      set -eu -o pipefail

      if [[ "$(params.verbose)" == "true" ]] ; then
        set -x
      fi

      IP=$(cat $(results.ip.path))

      START_TIME=${SECONDS}
      while true; do
        RESULT=$(ssh -i /tekton/home/ssh-key-pair/ssh-privatekey -o StrictHostKeyChecking=no redhat@${IP} echo "ready" || true)
        test "${RESULT}" = "ready" && break
        echo "Waiting for VM to become ready... ($((${SECONDS} - ${START_TIME}))s)"
        sleep 5
      done
  workspaces:
  - name: secrets
    mountPath: /tekton/home/ssh-key-pair
    description: Secret volume containing SSH key pair for VM
