apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: edt
resources:
- fetch-asset.yaml
- generate-containerdisk-containerfile.yaml
- kubevirt-deploy-vm.yaml
- register-device.yaml
- run-image-builder.yaml
- s3-upload.yaml
- unregister-device.yaml
- waitfor-cluster-up.yaml
- waitfor-ssh.yaml