apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: build-release
  namespace: edt
spec:
  params:
    - name: git-repo-url
      description: 'git repo to use for device config'
    - name: git-revision
      description: 'git revision to use for device config'

  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: build-release-
        namespace: edt
      spec:
        serviceAccountName: pipeline
        timeout: 2h0m0s
        pipelineRef:
          name: build-release

        params:
        - name: url
          value: $(tt.params.git-repo-url)
        - name: revision
          value: $(tt.params.git-revision)
        - name: s3-bucket
          value: 'cdn.redhat.edge-lab.net'
        - name: s3-prefix
          value: ''
        - name: s3-acl
          value: 'public-read'
        - name: verbose
          value: 'true'
        - name: ip
          value: '10.129.4.29'

        workspaces:
        - name: workspace
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
              storageClassName: gp2
              volumeMode: Filesystem
        - name: secrets
          secret:
            secretName: vm-ssh-keys
        - name: aws-creds
          secret:
            secretName: aws-creds

---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: build-release
  namespace: edt
spec:
  params:
    - name: git-repo-url
      value: $(body.repository.url)
    - name: git-commit-id
      value: $(body.head_commit.id)
    - name: git-ref
      value: $(body.ref)
