apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: test-device-provisions
  namespace: edt
spec:
  params:
    - name: imagestream-name
      description: 'git repo to use for device config'

  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: test-device-provisions-
        namespace: edt
      spec:
        serviceAccountName: pipeline
        timeout: 1h0m0s
        pipelineRef:
          name: test-device-provisions

        params:
        - name: diskimage
          value: $(tt.params.imagestream-name)
        - name: git-repo
          value: 'git@github.com:redhat-et/ushift.git'
        - name: git-reftag
          value: ci
        - name: cores
          value: '2'
        - name: memory
          value: '2Gi'

        workspaces:
        - name: ssh-keys
          secret:
            secretName: vm-ssh-keys
        - name: aws-creds
          secret:
            secretName: aws-creds

---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: test-device-provisions
  namespace: edt
spec:
  params:
  - name: imagestream-name
    value: $(body.metadata.name)
  - name: imagestream-namespace
    value: $(body.metadata.namespace)