apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: ushift-event-listener
  namespace: edt
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
      - ref: test-ushift-deploys
      template:
        name: test-ushift-deploys
      interceptors:
        - cel:
            filter: "body.ref.truncate(14) == 'refs/heads/o3s' || body.ref.truncate(15) == 'refs/heads/pods'"
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: el-ushift-event-listener
  namespace: edt
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: ushift-event-listener
spec:
  host: el-ushift-event-listener-edt.apps.edge-lab.aws.octo.edge-sites.net
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-ushift-event-listener
    weight: 100
  wildcardPolicy: None
