apiVersion: tekton.dev/v1beta1 
kind: Pipeline 
metadata:
  name: build-containerdisk
  namespace: edt
spec: 
  workspaces: 
  - name: workspace

  params: 
  - name: url
    type: string
    description: URL of the disk image in .raw or .qcow2 format
  - name: sha256_checksum
    type: string
    description: SHA256 checksum to verify asset download (if empty, don't verify)
    default: ''
  - name: uncompress
    description: uncompress asset (if compressed)
    type: string
    default: 'true'
  - name: image
    type: string
    description: container image to build
  - name: verbose
    description: 'log the commands used during execution'
    type: string
    default: 'false'

  tasks: 
  - name: fetch-diskimage
    taskRef:
      name: fetch-asset
      kind: Task
    params:
    - name: url
      value: $(params.url)
    - name: sha256_checksum
      value: $(params.sha256_checksum)
    - name: uncompress
      value: $(params.uncompress)
    - name: verbose
      value: $(params.verbose)
    workspaces:
    - name: output
      workspace: workspace

  - name: generate-containerfile
    taskRef:
      name: generate-containerdisk-containerfile
      kind: Task
    params:
    - name: filename
      value: '$(tasks.fetch-diskimage.results.filename)'
    - name: verbose
      value: $(params.verbose)
    workspaces:
    - name: output
      workspace: workspace
    runAfter:
    - fetch-diskimage

  - name: build-and-push
    taskRef:
      name: buildah
      kind: ClusterTask
    params:
    - name: TLSVERIFY
      value: 'false'
    - name: IMAGE
      value: 'image-registry.openshift-image-registry.svc:5000/edt/$(params.image):latest'
    - name: DOCKERFILE
      value: 'Containerfile'
    workspaces:
    - name: source
      workspace: workspace
    runAfter:
    - generate-containerfile

  - name: set-local-lookup
    taskRef:
      name: openshift-client
      kind: ClusterTask
    params:
    - name: ARGS
      value:
      - patch
      - -n
      - edt
      - is/$(params.image)
      - -p
      - '{"spec":{"lookupPolicy":{"local":true}}}'
    runAfter:
    - build-and-push
