apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-release
  namespace: edt
spec:
  workspaces:
  - name: workspace
  - name: secrets
  - name: aws-creds
  params:
  - name: url
    type: string
    description: 'URL of the git repo containing the ostree compose configs'
  - name: revision
    type: string
    description: 'git revision to checkout (branch, tag, sha, ref…)'
    default: 'main'
  - name: s3-bucket
    description: 'S3 bucket to upload to'
    type: string
  - name: s3-prefix
    description: 'prefix (path) for S3 keys to use'
    type: string
  - name: s3-acl
    description: 'ACL for uploaded objects'
    type: string
    default: 'priate'
  - name: verbose
    description: 'log the commands used during execution'
    type: string
    default: 'true'
  - name: ip
    description: 'IP address of the builder VM'
    type: string
  - name: variant
    description: 'main, o3s or pods'
    default: 'o3s'
  tasks:
  - name: fetch-configs
    taskRef:
      name: git-clone
      kind: ClusterTask
    params:
    - name: url
      value: $(params.url)
    - name: revision
      value: $(params.revision)
    - name: verbose
      value: $(params.verbose)
    workspaces:
    - name: output
      workspace: workspace
  - name: build-image
    taskRef:
      name: run-image-builder
      kind: Task
    params:
    - name: ip
      value: "$(params.ip)"
    - name: user
      value: 'redhat'
    - name: verbose
      value: $(params.verbose)
    workspaces:
    - name: output
      workspace: workspace
    - name: secrets
      workspace: secrets
    runAfter:
    - fetch-configs
  - name: s3-upload
    taskRef:
      name: s3-upload
      kind: Task
    params:
    - name: ip
      value: "$(params.ip)"
    - name: user
      value: 'redhat'
    - name: s3-bucket
      value: $(params.s3-bucket)
    - name: s3-prefix
      value: $(params.s3-prefix)
    - name: s3-acl
      value: $(params.s3-acl)
    - name: verbose
      value: $(params.verbose)
    runAfter:
    - build-image
    workspaces:
    - name: output
      workspace: workspace
    - name: secrets
      workspace: secrets
    - name: aws-creds
      workspace: aws-creds
