apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: osdisk_fedora33
spec:
  lookupPolicy:
    local: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: osdisk_fiot33
spec:
  lookupPolicy:
    local: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: osdisk_rhel8
spec:
  lookupPolicy:
    local: true
