apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-containerdisk-fedora33
  namespace: edt
spec:
  pipelineRef:
    name: build-containerdisk
  params:
  - name: url
    value: >-
      https://download.fedoraproject.org/pub/fedora/linux/releases/33/Cloud/x86_64/images/Fedora-Cloud-Base-33-1.2.x86_64.qcow2
  - name: sha256_checksum
    value: '7a2b3cc3bb3a92ce927e685d33efe8efd75577efbe207b267cb66f68afae7ce9'
  - name: image
    value: osdisk_fedora33
  - name: verbose
    value: 'true'
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces: 
  - name: workspace 
    volumeClaimTemplate: 
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 4Gi
        storageClassName: gp2
        volumeMode: Filesystem
