apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-containerdisk-fiot-o3s
  namespace: edt
spec:
  pipelineRef:
    name: build-containerdisk
  params:
  - name: url
    value: >-
      http://cdn.redhat.edge-lab.net/releases/fiot-o3s/latest/x86_64/fiot-o3s.img
  - name: sha256_checksum
    value: ''
  - name: image
    value: osdisk_fiot-o3s
  - name: verbose
    value: 'true'
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 25Gi
        storageClassName: gp2
        volumeMode: Filesystem
