apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-containerdisk-fiot-pods
  namespace: edt
spec:
  pipelineRef:
    name: build-containerdisk
  params:
  - name: url
    value: >-
      https://s3.eu-central-1.amazonaws.com/cdn.redhat.edge-lab.net/releases/fiot-pods/latest/x86_64/fiot-pods.img
  - name: sha256_checksum
    value: ''
  - name: image
    value: osdisk_fiot-pods
  - name: verbose
    value: 'true'
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 15Gi
        storageClassName: gp2
        volumeMode: Filesystem
