apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-containerdisk-rhel8
  namespace: edt
spec:
  pipelineRef:
    name: build-containerdisk
  params:
  - name: url
    value: >-
      YOUR_DOWNLOAD_URL_FROM_ACCESS_REDHAT_COM
  - name: sha256_checksum
    value: '321c20a732419472ba584ea34cd2cab79db2ea1790abe467ea3c0e2ca521a6b7'
  - name: image
    value: 'image-registry.openshift-image-registry.svc:5000/edt/osdisk_rhel8:latest'
  - name: verbose
    value: 'true'
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces: 
  - name: workspace 
    volumeClaimTemplate: 
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 4Gi
        storageClassName: gp2
        volumeMode: Filesystem
