apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-containerdisk-fiot-main
  namespace: edt
spec:
  pipelineRef:
    name: build-containerdisk
  params:
  - name: url
    value: >-
      https://s3.eu-central-1.amazonaws.com/cdn.redhat.edge-lab.net/releases/fiot-main/latest/x86_64/fiot-main.raw
  - name: sha256_checksum
    value: ''
  - name: image
    value: osdisk_fiot-main
  - name: verbose
    value: 'true'
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces: 
  - name: workspace 
    volumeClaimTemplate: 
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 25Gi
        storageClassName: gp2
        volumeMode: Filesystem
