apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: aws-efs-operator
  namespace: openshift-operators
spec:
  source: community-operators
  sourceNamespace: openshift-marketplace
  name: aws-efs-operator
  channel: "stable"
